<a href="https://colab.research.google.com/github/ignacioquirogaa/Curso-Coder-DS/blob/main/ColabCursoCoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase 2

In [1]:
valores = [200, 225, 232, 221, 243, 256, 255]
dias = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']

In [2]:
import numpy as np

valores = [200, 225, 232, 221, 243, 256, 255]
dias = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo']

# Calcular la diferencia entre valores consecutivos
diferencias = np.diff(valores)

# Detectar retrocesos en los valores
for i, cambio in enumerate(diferencias, start=1):
    if cambio < 0:
        print(f"🔻 Hubo un retroceso el día {dias[i]} (valor: {valores[i]} vs día anterior: {valores[i-1]})")

🔻 Hubo un retroceso el día Jueves (valor: 221 vs día anterior: 232)
🔻 Hubo un retroceso el día Domingo (valor: 255 vs día anterior: 256)


✅ Utilizando un ciclo (for o while), obtené las siguientes métricas para cada columna del DataFrame (cada acción):

Media (promedio)
Desviación estándar
Varianza
📌 Sugerencia: Podés utilizar las funciones:

.mean(), .std(), .var()

In [4]:
df = {"Valores": valores, "Días": dias}

In [5]:
import pandas as pd

df = pd.DataFrame(df)
df

Valores       Días
0      200      Lunes
1      225     Martes
2      232  Miércoles
3      221     Jueves
4      243    Viernes
5      256     Sábado
6      255    Domingo

# Clase 3

In [6]:
# Crear un vector desde una lista
v = np.array([1, 2, 3, 4])
print(v)

[1 2 3 4]


In [7]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

# Suma elemento a elemento
print(a + b)

# Multiplicación escalar
print(a * 2)

# Potencia
print(b ** 2)

[11 22 33]
[20 40 60]
[1 4 9]


In [10]:
# Matriz 2x2
A = np.array([[1, 2],
              [3, 4]])

# Transpuesta
print(A.T)

# Inversa
print(np.linalg.inv(A))

# Producto matricial
B = np.array([[5, 6],
              [7, 8]])
print(np.dot(A, B))

[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[19 22]
 [43 50]]


In [13]:
import pandas as pd

In [14]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print(s)

a    10
b    20
c    30
dtype: int64


In [18]:
data = {
    'nombre': ['Ana', 'Luis', 'Juan'],
    'edad': [23, 35, 29],
    'ciudad': ['Córdoba', 'Buenos Aires', 'Rosario']
}

df = pd.DataFrame(data)
print(df)

  nombre  edad        ciudad
0    Ana    23       Córdoba
1   Luis    35  Buenos Aires
2   Juan    29       Rosario


In [21]:
# Seleccionar columna
print(df['edad'])

# Filtrar por condición
#print(df[df['edad'] > 30])

# Acceder por etiqueta o posición
#print(df.loc[1])    Fila con índice 1
#print(df.iloc[0])  # Primera fila

0    23
1    35
2    29
Name: edad, dtype: int64
